### ISSUE TITLE
i can add a c++ Book alocation problem

### ISSUE THREAD

**Issue by Deepankar1484** [funway009/HacktoberFEST-2023#9]
Hello @funway009  , Hope you are doing great today.
As some students are always confused in Book alocation problem i have got the easiest and fastest solution for the same.
please assign me the work and please add hacktober fest label.
I would be very thankful of yours.

**Comment by sudheerkumar67** [comment]
@Deepankar1484  Do it now.

**Comment by priysnty123** [comment]
> @Deepankar1484 Do it now.

hello @Deepankar1484 I am commiting the important topics code of linked list please check it earlier , i got your repository today itself so i commit it immedeately. please check it soon.
